# Generated by Django 5.2.7 on 2025-11-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_user_followed_by_user_following_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(default='No text entered'),
        ),
    ]
