# Generated by Django 5.2.7 on 2025-11-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_user_bio_user_image_user_joindate_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to='profile_pics'),
        ),
    ]
