# Generated by Django 5.2.7 on 2025-11-07 15:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='member_likes',
            field=models.ManyToManyField(related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
